### ISSUE TITLE
any help to make it work it Windows VS2017?

### ISSUE THREAD

**Issue by moebiussurfing** [borg/ofxGist#3]
Hey @borg ,
Do you think you can update o tell me two cents about how to do it to use on Windows?
I have seen this other newer addon that maybe can run as an alternative for openAl:
https://github.com/npisanti/ofxAudioFile

**Comment by moebiussurfing** [comment]
it worked for live input processing using this code:
https://forum.openframeworks.cc/t/audio-analysis-for-windows/26121/9?u=moebiussurfing

**Comment by borg** [comment]
Hey, sorry haven't had a chance to look at this with the apocalypse and all...and haven't used this addon for a while...although I did an update in dev branch...vague memory that also fixed the abstract class issue (came with oF1.0 I think). 

Anyway, I'm pretty sure you can get the sound buffer out of ofMaxim like so if you want to, and hopefully works just fine.
https://github.com/edap/examplesOfxMaxim/blob/master/03-FFT-File/src/ofApp.cpp

I saw you found another solution already. Great! Sorry couldn't help.
